include: package:flutter_lints/flutter.yaml

#
# Keep rules alphabetic
#

linter:
  rules:
    - always_declare_return_types
    - always_use_package_imports
    - avoid_catches_without_on_clauses
    - avoid_catching_errors
    - avoid_field_initializers_in_const_classes
    - avoid_positional_boolean_parameters
    - avoid_private_typedef_functions
    - avoid_returning_this
    - avoid_setters_without_getters
    - avoid_unused_constructor_parameters
    - avoid_void_async
    - cancel_subscriptions
    - close_sinks
    - join_return_with_assignment
    - lines_longer_than_80_chars
    - one_member_abstracts
    - only_throw_errors
    - prefer_asserts_in_initializer_lists
    - prefer_asserts_with_message
    - prefer_final_in_for_each
    - prefer_final_locals
    - prefer_if_elements_to_conditional_expressions
    - prefer_single_quotes
    - sort_constructors_first
    - sort_unnamed_constructors_first
    - throw_in_finally
    - unnecessary_lambdas
    - unnecessary_parenthesis
    - unnecessary_statements
    - use_setters_to_change_properties
    - use_super_parameters
    - use_to_and_as_if_applicable

analyzer:
  strong-mode:
    implicit-casts: false
  errors:
    always_declare_return_types: warning
    always_use_package_imports: warning
    annotate_overrides: warning
    avoid_catches_without_on_clauses: warning
    avoid_catching_errors: warning
    avoid_empty_else: warning
    avoid_field_initializers_in_const_classes: warning
    avoid_function_literals_in_foreach_calls: warning
    avoid_init_to_null: warning
    avoid_null_checks_in_equality_operators: warning
    avoid_positional_boolean_parameters: error
    avoid_print: warning
    avoid_private_typedef_functions: warning
    avoid_relative_lib_imports: warning
    avoid_renaming_method_parameters: warning
    avoid_returning_null_for_void: warning
    avoid_returning_this: warning
    avoid_setters_without_getters: warning
    avoid_types_as_parameter_names: warning
    avoid_unnecessary_containers: warning
    avoid_unused_constructor_parameters: warning
    avoid_void_async: warning
    await_only_futures: warning
    body_might_complete_normally_nullable: warning
    camel_case_extensions: warning
    camel_case_types: error
    cancel_subscriptions: warning
    close_sinks: warning
    constant_identifier_names: warning
    control_flow_in_finally: warning
    curly_braces_in_flow_control_structures: warning
    dead_code: error
    depend_on_referenced_packages: warning
    empty_catches: warning
    empty_constructor_bodies: warning
    empty_statements: warning
    file_names: warning
    hash_and_equals: warning
    implementation_imports: error
    import_of_legacy_library_into_null_safe: error
    invalid_use_of_protected_member: error
    invalid_use_of_visible_for_testing_member: error
    join_return_with_assignment: warning
    library_names: warning
    library_prefixes: warning
    lines_longer_than_80_chars: warning
    missing_enum_constant_in_switch: error
    missing_required_param: error
    missing_return: error
    no_duplicate_case_values: warning
    no_logic_in_create_state: warning
    non_constant_identifier_names: warning
    null_closures: warning
    one_member_abstracts: warning
    only_throw_errors: warning
    parameter_assignments: warning
    prefer_adjacent_string_concatenation: warning
    prefer_asserts_in_initializer_lists: warning
    prefer_asserts_with_message: warning
    prefer_collection_literals: warning
    prefer_conditional_assignment: warning
    prefer_const_constructors_in_immutables: warning
    prefer_const_constructors: warning
    prefer_const_declarations: warning
    prefer_const_literals_to_create_immutables: warning
    prefer_contains: warning
    prefer_equal_for_default_values: warning
    prefer_final_fields: warning
    prefer_final_in_for_each: warning
    prefer_final_locals: warning
    prefer_for_elements_to_map_fromIterable: warning
    prefer_function_declarations_over_variables: warning
    prefer_generic_function_type_aliases: warning
    prefer_if_elements_to_conditional_expressions: warning
    prefer_if_null_operators: warning
    prefer_initializing_formals: warning
    prefer_inlined_adds: warning
    prefer_interpolation_to_compose_strings: warning
    prefer_is_empty: warning
    prefer_is_not_empty: warning
    prefer_single_quotes: warning
    slash_for_doc_comments: warning
    sort_constructors_first: warning
    sort_unnamed_constructors_first: warning
    throw_in_finally: warning
    type_init_formals: warning
    unnecessary_const: warning
    unnecessary_getters_setters: warning
    unnecessary_import: warning
    unnecessary_lambdas: warning
    unnecessary_new: error
    unnecessary_null_aware_assignments: warning
    unnecessary_null_in_if_null_operators: warning
    unnecessary_overrides: warning
    unnecessary_parenthesis: warning
    unnecessary_statements: warning
    unnecessary_type_check: warning
    unrelated_type_equality_checks: warning
    unused_element: warning
    unused_import: warning
    unused_local_variable: warning
    use_full_hex_values_for_flutter_colors: warning
    use_rethrow_when_possible: warning
    use_setters_to_change_properties: warning
    use_super_parameters: warning
    use_to_and_as_if_applicable: warning
    valid_regexps: warning

    deprecated_member_use_from_same_package: info
    deprecated_member_use: info
    todo: info
    use_key_in_widget_constructors: info

  exclude:
    - "**.g.dart"
    - "**.gr.dart"
    - "bin/cache/**"
    - "test/**.mocks.dart"
    - "lib/client/generated/**"
